
/*
DDL Script : Create silver Tables

-------------------------------------------------------------------

Creating tables with existing table based data

Silver layer: cleaned, standardized, validated and integrated clinical data
*/

IF OBJECT_ID('gold.dim_organization','U') IS NOT NULL
	DROP TABLE gold.dim_organization;
CREATE TABLE gold.dim_organization(
	organization_key INT IDENTITY(1,1), -- surrogate key
	organization_id NVARCHAR(255), -- natural key
	organization_name NVARCHAR(255), 
	organization_address NVARCHAR(255),
	organization_city NVARCHAR(255),
	organization_state NVARCHAR(50),
	organization_zip NVARCHAR(50),
	organization_phone NVARCHAR(50),
	revenue DECIMAL(18,2),
	utilization INT,
	dwh_create_date DATETIME2 DEFAULT GETDATE()
);

IF OBJECT_ID('gold.dim_patient','U') IS NOT NULL
    DROP TABLE gold.dim_patient;
CREATE TABLE gold.dim_patient(
    patient_key         INT IDENTITY(1,1),  -- surrogate key, auto-generated by SQL Server
    patient_id          NVARCHAR(255),       -- natural key from source (UUID)
    first_name          NVARCHAR(50),        -- cleaned first name (numbers removed in Silver)
    last_name           NVARCHAR(50),        -- cleaned last name (numbers removed in Silver)
    full_name           NVARCHAR(100),       -- derived: first + last combined for display
    birthdate           DATE,
    deathdate           DATE,                -- NULL means patient is still alive
    age                 INT,                 -- derived: calculated at death or current date
    is_deceased         INT,                 -- derived flag: 1 = deceased, 0 = alive
    gender              NVARCHAR(50),        -- standardized: 'male' / 'female' / 'unknown'
    race                NVARCHAR(50),
    ethnicity           NVARCHAR(255),
    marital_status      NVARCHAR(50),        -- standardized: 'married' / 'single' / 'unknown'
    birthplace          NVARCHAR(255),
    address             NVARCHAR(255),
    city                NVARCHAR(50),
    state               NVARCHAR(50),
    county              NVARCHAR(50),
    zip                 NVARCHAR(50),
    healthcare_expenses DECIMAL(18,2),
    healthcare_coverage DECIMAL(18,2),
    dwh_create_date     DATETIME2 DEFAULT GETDATE()
);


IF OBJECT_ID('gold.dim_payer','U') IS NOT NULL
    DROP TABLE gold.dim_payer;
CREATE TABLE gold.dim_payer(
    payer_key               INT IDENTITY(1,1),  -- surrogate key, auto-generated
    payer_id                NVARCHAR(255),       -- natural key from source (UUID)
    payer_name              NVARCHAR(255),
    payer_address           NVARCHAR(255),       -- prefixed to avoid ambiguity in joins
    payer_city              NVARCHAR(255),
    payer_state             NVARCHAR(50),
    payer_zip               NVARCHAR(50),
    payer_phone             NVARCHAR(50),
    amount_covered          DECIMAL(18,2),       -- total amount covered by payer
    amount_uncovered        DECIMAL(18,2),       -- total amount not covered
    revenue                 DECIMAL(18,2),
    qols_avg                FLOAT,              -- quality of life score [0-1], capped in Silver
    member_months           INT,                 -- total member months of coverage
    dwh_create_date         DATETIME2 DEFAULT GETDATE()
);

IF OBJECT_ID('gold.dim_provider','U') IS NOT NULL
	DROP TABLE gold.dim_provider;
CREATE TABLE gold.dim_provider(
    provider_key INT IDENTITY(1,1),
	provider_id NVARCHAR(255),
	name NVARCHAR(255),
	gender NVARCHAR(50),
	specialty NVARCHAR(50),
	city NVARCHAR(255),
	state NVARCHAR(50),
	zip NVARCHAR(50),
	utilization INT,
    organization_name NVARCHAR(255),
    organization_city NVARCHAR(255),
    organization_state NVARCHAR(50),
	dwh_create_date DATETIME2 DEFAULT GETDATE()
);

IF OBJECT_ID('gold.fact_encounter','U') IS NOT NULL
	DROP TABLE gold.fact_encounter;
CREATE TABLE gold.fact_encounter(
	encounter_key INT IDENTITY(1,1), -- surogate key
	encounter_id NVARCHAR(255), -- encounter id
	patient_key INT, -- primary key from patient table
	organization_key INT, -- primary key from organization table
	provider_key INT, -- primary key from provider table
	payer_key INT, -- primary key from payer table
	date_key INT, -- primary key from date table
	encounterclass NVARCHAR(255),
	reasondescription NVARCHAR(255),
	description NVARCHAR(500),
	base_encounter_cost DECIMAL(18,2),
	total_claim_cost DECIMAL(18,2),
	payer_coverage DECIMAL(18,2),
	dwh_create_date DATETIME2 DEFAULT GETDATE()
);

IF OBJECT_ID('gold.dim_date', 'U') IS NOT NULL
    DROP TABLE gold.dim_date;
CREATE TABLE gold.dim_date (
    date_key        INT,           -- e.g. 20100101 - used as FK in fact tables
    full_date       DATE,          -- actual date value
    year            INT,           -- 2010
    month           INT,           -- 1
    month_name      NVARCHAR(20),  -- January
    quarter         INT,           -- 1
    quarter_name    NVARCHAR(10),  -- Q1
    day_of_month    INT,           -- 1
    day_of_week     INT,           -- 1 (Monday) to 7 (Sunday)
    day_name        NVARCHAR(20),  -- Monday
    is_weekend      INT,           -- 1 if Saturday/Sunday, else 0
    is_weekday      INT,           -- 1 if Mon-Fri, else 0
    dwh_create_date DATETIME2 DEFAULT GETDATE()
);
GO
